# Generated by Django 4.2.16 on 2024-09-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
